version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: tts_app
      POSTGRES_USER: tts_user
      POSTGRES_PASSWORD: tts_eugene
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn app:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://tts_user:tts_eugene@db/tts_app
    depends_on:
      - db

volumes:
  postgres_data:
